use serde::{Deserialize, Serialize};

use super::safety::SafetyLevel;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ScanCategory {
    NodeDependencies,
    NodeCaches,
    DockerImages,
    DockerBuildCache,
    XcodeSimulators,
    XcodeDerivedData,
    GradleCache,
    SystemCaches,
    HomebrewCache,
    RustTargets,
    CargoCaches,
    PythonCaches,
    PythonVenvs,
    GoCache,
    MavenCache,
    RubyCache,
    DotnetCache,
    FlutterCache,
    CocoaPodsCache,
    ComposerCache,
    IdeCaches,
    XcodeDeviceSupport,
    XcodeArchives,
    BrowserCaches,
    SystemLogs,
    IosBackups,
    Trash,
    OldDownloads,
    TimeMachineSnapshots,
}

impl ScanCategory {
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::NodeDependencies => "JavaScript Project Dependencies",
            Self::NodeCaches => "JavaScript Package Manager Caches",
            Self::DockerImages => "Docker Unused Images",
            Self::DockerBuildCache => "Docker Build Cache",
            Self::XcodeSimulators => "Xcode Simulators & Runtimes",
            Self::XcodeDerivedData => "Xcode Build Data",
            Self::GradleCache => "Android/Gradle Build Cache",
            Self::SystemCaches => "System Caches",
            Self::HomebrewCache => "Homebrew Package Cache",
            Self::RustTargets => "Rust Build Artifacts",
            Self::CargoCaches => "Cargo Registry & Cache",
            Self::PythonCaches => "Python Caches",
            Self::PythonVenvs => "Python Virtual Environments",
            Self::GoCache => "Go Build & Module Cache",
            Self::MavenCache => "Maven/Java Repository Cache",
            Self::RubyCache => "Ruby Gem & Bundler Cache",
            Self::DotnetCache => ".NET/NuGet Cache",
            Self::FlutterCache => "Flutter/Dart Cache",
            Self::CocoaPodsCache => "CocoaPods Cache",
            Self::ComposerCache => "PHP Composer Cache",
            Self::IdeCaches => "IDE & Editor Caches",
            Self::XcodeDeviceSupport => "Xcode Device Support Files",
            Self::XcodeArchives => "Xcode Archives",
            Self::BrowserCaches => "Browser Caches",
            Self::SystemLogs => "System & Application Logs",
            Self::IosBackups => "iOS Device Backups",
            Self::Trash => "Trash",
            Self::OldDownloads => "Old Downloads",
            Self::TimeMachineSnapshots => "Time Machine Local Snapshots",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            Self::NodeDependencies => "Downloaded libraries for JavaScript projects. Automatically re-downloaded when you open the project.",
            Self::NodeCaches => "Package manager download caches. Clearing these may slow your next install slightly.",
            Self::DockerImages => "Container images not used by any running container. Re-pulled when needed.",
            Self::DockerBuildCache => "Cached layers from building containers. Rebuilt automatically on next build.",
            Self::XcodeSimulators => "iOS/watchOS/tvOS simulator devices and runtimes. Re-downloaded from Xcode when needed.",
            Self::XcodeDerivedData => "Build artifacts from Xcode projects. Rebuilt automatically when you open the project.",
            Self::GradleCache => "Cached dependencies for Android/Java projects. Re-downloaded on next build.",
            Self::SystemCaches => "Application caches in your Library folder. Apps regenerate these as needed.",
            Self::HomebrewCache => "Downloaded package files from Homebrew. No longer needed after installation.",
            Self::RustTargets => "Compiled build artifacts in Rust projects. Rebuilt automatically with cargo build.",
            Self::CargoCaches => "Downloaded crate sources and registry index. Re-downloaded when needed.",
            Self::PythonCaches => "pip download cache and __pycache__ bytecode files. Regenerated automatically.",
            Self::PythonVenvs => "Python virtual environments in projects. Recreated with pip install.",
            Self::GoCache => "Go compiled packages and build cache. Rebuilt automatically on next build.",
            Self::MavenCache => "Downloaded Java/Kotlin dependencies. Re-downloaded on next build.",
            Self::RubyCache => "Downloaded gem files and bundler cache. Re-downloaded with bundle install.",
            Self::DotnetCache => "NuGet package cache and build outputs. Re-downloaded on next build.",
            Self::FlutterCache => "Dart pub cache and Flutter tool artifacts. Re-downloaded when needed.",
            Self::CocoaPodsCache => "Downloaded CocoaPods specs and pods. Re-downloaded with pod install.",
            Self::ComposerCache => "Downloaded PHP packages. Re-downloaded with composer install.",
            Self::IdeCaches => "Editor workspace storage and old version data. Regenerated by the IDE.",
            Self::XcodeDeviceSupport => "Debug symbols for iOS devices you've connected. Re-downloaded when you connect the device again.",
            Self::XcodeArchives => "Archived builds from Xcode. Review before removing if you need to submit older builds.",
            Self::BrowserCaches => "Cached web content from browsers. Rebuilt automatically as you browse.",
            Self::SystemLogs => "Application and system log files. Safe to remove; new logs are created as needed.",
            Self::IosBackups => "Local backups of iPhones and iPads. Check if you have iCloud backups before removing.",
            Self::Trash => "Files you've already deleted but haven't emptied from Trash yet.",
            Self::OldDownloads => "Files in your Downloads folder older than 90 days.",
            Self::TimeMachineSnapshots => "Local Time Machine snapshots stored on this disk. New snapshots are created automatically.",
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::NodeDependencies => "node_dependencies",
            Self::NodeCaches => "node_caches",
            Self::DockerImages => "docker_images",
            Self::DockerBuildCache => "docker_build_cache",
            Self::XcodeSimulators => "xcode_simulators",
            Self::XcodeDerivedData => "xcode_derived_data",
            Self::GradleCache => "gradle_cache",
            Self::SystemCaches => "system_caches",
            Self::HomebrewCache => "homebrew_cache",
            Self::RustTargets => "rust_targets",
            Self::CargoCaches => "cargo_caches",
            Self::PythonCaches => "python_caches",
            Self::PythonVenvs => "python_venvs",
            Self::GoCache => "go_cache",
            Self::MavenCache => "maven_cache",
            Self::RubyCache => "ruby_cache",
            Self::DotnetCache => "dotnet_cache",
            Self::FlutterCache => "flutter_cache",
            Self::CocoaPodsCache => "cocoapods_cache",
            Self::ComposerCache => "composer_cache",
            Self::IdeCaches => "ide_caches",
            Self::XcodeDeviceSupport => "xcode_device_support",
            Self::XcodeArchives => "xcode_archives",
            Self::BrowserCaches => "browser_caches",
            Self::SystemLogs => "system_logs",
            Self::IosBackups => "ios_backups",
            Self::Trash => "trash",
            Self::OldDownloads => "old_downloads",
            Self::TimeMachineSnapshots => "time_machine_snapshots",
        }
    }

    pub fn from_str(s: &str) -> Self {
        match s {
            "node_dependencies" => Self::NodeDependencies,
            "node_caches" => Self::NodeCaches,
            "docker_images" => Self::DockerImages,
            "docker_build_cache" => Self::DockerBuildCache,
            "xcode_simulators" => Self::XcodeSimulators,
            "xcode_derived_data" => Self::XcodeDerivedData,
            "gradle_cache" => Self::GradleCache,
            "system_caches" => Self::SystemCaches,
            "homebrew_cache" => Self::HomebrewCache,
            "rust_targets" => Self::RustTargets,
            "cargo_caches" => Self::CargoCaches,
            "python_caches" => Self::PythonCaches,
            "python_venvs" => Self::PythonVenvs,
            "go_cache" => Self::GoCache,
            "maven_cache" => Self::MavenCache,
            "ruby_cache" => Self::RubyCache,
            "dotnet_cache" => Self::DotnetCache,
            "flutter_cache" => Self::FlutterCache,
            "cocoapods_cache" => Self::CocoaPodsCache,
            "composer_cache" => Self::ComposerCache,
            "ide_caches" => Self::IdeCaches,
            "xcode_device_support" => Self::XcodeDeviceSupport,
            "xcode_archives" => Self::XcodeArchives,
            "browser_caches" => Self::BrowserCaches,
            "system_logs" => Self::SystemLogs,
            "ios_backups" => Self::IosBackups,
            "trash" => Self::Trash,
            "old_downloads" => Self::OldDownloads,
            "time_machine_snapshots" => Self::TimeMachineSnapshots,
            _ => Self::SystemCaches,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanItem {
    pub id: String,
    pub path: String,
    pub display_name: String,
    pub description: String,
    pub size_bytes: u64,
    pub safety: SafetyLevel,
    pub category: ScanCategory,
    pub last_modified: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategoryResult {
    pub category: ScanCategory,
    pub display_name: String,
    pub description: String,
    pub total_bytes: u64,
    pub items: Vec<ScanItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanResult {
    pub started_at: i64,
    pub completed_at: Option<i64>,
    pub total_bytes: u64,
    pub categories: Vec<CategoryResult>,
}
